---
  kind: pipeline
  type: docker
  name: default

  steps:
  - name: build
    image: rknt/dissertation_builder:0.5
    commands:
    - make clean
    - make all
    - chmod -R 777 _build
  
  - name: test_links
    image: becheran/mlc
    commands:
    - mlc -t html --ignore-links "http*://doi.org*" --ignore-path "./_build/diss-haarhoff.standalone.html"

