#!/bin/bash

set -e

name=${1%.*}
outputdir=$(dirname $1)
tex=${1%.*}.tex
pdf=${1%.*}.pdf
ppm=${1%.*}-1.ppm
png=${1%.*}.png

pdflatex -output-directory $outputdir -interaction=nonstopmode $tex
pdfcrop $pdf $pdf -margins "5 5 5 5"
pdftoppm -r 300 $pdf $name
convert $ppm $png

echo "Removing temporary files..."
rm -v $ppm
rm -v ${name}.aux
rm -v ${name}.log

