#!/bin/bash

set -e

name=${1%.*}
outputdir=$(dirname $1)
tex=${1%.*}.tex
pdf=${1%.*}.pdf

pdflatex -output-directory $outputdir -interaction=nonstopmode $tex
pdfcrop $pdf $pdf -margins "5 5 5 5"

rm -v ${name}.aux
rm -v ${name}.log
